language: ruby
rvm:
  - 2.0.0
  - 2.1.2
  - 2.2.0
script:
  - rm -rf spec/fixtures/vcr_cassettes/
  - if [ -e /tmp/bravo* ]; then rm /tmp/bravo*; fi
  - bundle exec rspec spec --format=progress
  - bundle exec rubocop
